### ISSUE TITLE
Bug: strange square

### ISSUE THREAD

**Issue by ikanakova** [fenimore/badreads#11] opened 2021-07-13 13:06 UTC
#### Issue description
Strange square during book search.

#### Steps to reproduce the issue

1.  ➕
2. search box Title, Author or ISBN + 🔍
3. tap in search box

#### What's the expected result?

- only I-cursor

#### What's the actual result?

- Square

#### Additional details / screenshot

- Android 10
- App version: 0.1.6 (f-droid)
- Screenshot:
![Screenshot](https://user-images.githubusercontent.com/38765251/125456422-e18826eb-4154-449d-bbed-d11dd39d8a4e.png)

**Comment by fenimore** [comment] 2021-07-13 21:07
Thanks for reporting this, it's a duplicate of another ticket, so I'll close this one. I'll get to it sooner or later!

**Closed** 2021-08-03 13:40 UTC
